name: Backend App CI

on:
  push:
    branches: [develop]
    paths:
      - 'src/backend-app/**'
  pull_request:
    branches: [develop]
    paths:
      - 'src/backend-app/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
    - run: dotnet restore ./src/backend-app/FitnessTracker.sln
    - run: dotnet build --no-restore ./src/backend-app/FitnessTracker.sln
    - run: dotnet test ./src/backend-app/FitnessTracker.sln