name: Client App CI

on:
  push:
    branches: [develop]
    paths:
      - 'src/client-app/**'
  pull_request:
    branches: [develop]
    paths:
      - 'src/client-app/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21'
    - run: npm install
      working-directory: ./src/client-app
    - run: npm run build
      working-directory: ./src/client-app